"""
Build reliable, higher-resolution cover metadata for the dashboard.

Adds/updates:
    - isbn13
    - image_url (Goodreads medium)
    - google_cover_url
    - google_cover_url_large

Google Books is queried once per ISBN and cached locally.

Important:
The old version stored Google's `thumbnail` URL. This version upgrades
old cache entries and stores a larger Google Books image URL as well.

Run:
    python src/add_cover_data.py
"""

import json
import os
import time
import urllib.error
import urllib.parse
import urllib.request

import pandas as pd


ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, "data")
OUT_DIR = os.path.join(DATA_DIR, "processed")
CACHE_PATH = os.path.join(OUT_DIR, ".google_books_cache.json")


def clean_isbn13(val):
    """Convert pandas numeric/string ISBN values to a clean 13-digit string."""
    if pd.isna(val):
        return None

    try:
        s = str(int(round(float(val))))
        return s if len(s) == 13 else None
    except (ValueError, TypeError):
        s = str(val).strip().replace("-", "")
        return s if len(s) == 13 and s.isdigit() else None


def _load_cache() -> dict:
    if os.path.exists(CACHE_PATH):
        try:
            with open(CACHE_PATH, encoding="utf-8") as f:
                data = json.load(f)

            return data if isinstance(data, dict) else {}

        except (OSError, json.JSONDecodeError):
            return {}

    return {}


def _save_cache(cache: dict) -> None:
    os.makedirs(OUT_DIR, exist_ok=True)

    with open(CACHE_PATH, "w", encoding="utf-8") as f:
        json.dump(
            cache,
            f,
            ensure_ascii=False,
            indent=2
        )


def _https(url: str) -> str:
    """
    Normalize Google image URLs.
    """
    return (
        str(url)
        .replace("http://", "https://")
        .replace("&edge=curl", "")
    )


def _zoom_url(url: str, zoom: int) -> str | None:
    """
    Ask Google Books for a larger rendition.

    Google image URLs commonly contain:
        zoom=1
        zoom=2

    We upgrade them to zoom=3 where possible.
    """

    if not url:
        return None

    url = _https(url)

    if "zoom=" in url:
        url = url.replace("zoom=1", f"zoom={zoom}")
        url = url.replace("zoom=2", f"zoom={zoom}")
        return url

    separator = "&" if "?" in url else "?"

    return f"{url}{separator}zoom={zoom}"


def _normalise_cached(value):
    """
    Return:
        (normal_url, large_url)

    Old cache entries were simple strings.
    New entries are dictionaries.
    """

    if isinstance(value, dict):
        return (
            value.get("url"),
            value.get("large_url"),
        )

    if isinstance(value, str) and value:
        return value, None

    return None, None


def fetch_google_cover(
    isbn13: str,
    cache: dict
) -> tuple[str | None, str | None]:
    """
    Look up Google Books by ISBN-13.

    Returns:
        normal_url
        large_url
    """

    cached_value = cache.get(isbn13)

    cached_normal, cached_large = _normalise_cached(
        cached_value
    )

    # Only trust cache entries generated by the new version.
    #
    # Old cache entries contain only the small thumbnail URL.
    # Those must be refreshed.
    if (
        isinstance(cached_value, dict)
        and cached_normal
        and cached_large
    ):
        return cached_normal, cached_large

    url = (
        "https://www.googleapis.com/books/v1/volumes?q="
        + urllib.parse.quote(f"isbn:{isbn13}")
    )

    normal = None
    large = None

    try:
        request = urllib.request.Request(
            url,
            headers={
                "User-Agent":
                    "book-recsys-dashboard/1.0"
            }
        )

        with urllib.request.urlopen(
            request,
            timeout=8
        ) as response:

            data = json.loads(
                response.read()
            )

        items = data.get("items") or []

        if items:

            volume_info = (
                items[0]
                .get("volumeInfo", {})
            )

            links = (
                volume_info
                .get("imageLinks", {})
                or {}
            )

            # --------------------------------------------------
            # Normal cover
            # --------------------------------------------------

            for key in (
                "extraLarge",
                "large",
                "medium",
                "thumbnail",
            ):
                if links.get(key):
                    normal = _https(
                        links[key]
                    )
                    break

            # --------------------------------------------------
            # Large cover
            # --------------------------------------------------

            for key in (
                "extraLarge",
                "large",
                "medium",
            ):
                if links.get(key):
                    large = _https(
                        links[key]
                    )
                    break

            # --------------------------------------------------
            # If Google only returned thumbnail,
            # generate a zoomed version.
            # --------------------------------------------------

            if normal and not large:
                large = _zoom_url(
                    normal,
                    3
                )

            # Make normal Google image somewhat larger too.
            if normal and "zoom=" in normal:
                normal = (
                    _zoom_url(
                        normal,
                        2
                    )
                    or normal
                )

            # Final large fallback.
            if normal and not large:
                large = _zoom_url(
                    normal,
                    3
                )

    except (
        urllib.error.URLError,
        urllib.error.HTTPError,
        TimeoutError,
        json.JSONDecodeError,
    ):
        normal = None
        large = None

    cache[isbn13] = {
        "url": normal,
        "large_url": large,
    }

    return normal, large


def main():

    os.makedirs(
        OUT_DIR,
        exist_ok=True
    )

    books = pd.read_csv(
        os.path.join(
            DATA_DIR,
            "books.csv"
        )
    )

    item_meta = pd.read_csv(
        os.path.join(
            OUT_DIR,
            "item_meta.csv"
        )
    )

    # ----------------------------------------------------------
    # ISBN
    # ----------------------------------------------------------

    books["isbn13_clean"] = (
        books["isbn13"]
        .map(clean_isbn13)
    )

    lookup = books.set_index(
        "book_id"
    )[
        [
            "isbn13_clean",
            "image_url"
        ]
    ]

    item_meta["isbn13"] = (
        item_meta["book_id"]
        .map(lookup["isbn13_clean"])
    )

    item_meta["image_url"] = (
        item_meta["book_id"]
        .map(lookup["image_url"])
    )

    # ----------------------------------------------------------
    # Google Books
    # ----------------------------------------------------------

    cache = _load_cache()

    google_urls = []
    google_large_urls = []

    total = len(item_meta)

    for idx, isbn in enumerate(
        item_meta["isbn13"]
    ):

        if idx % 200 == 0:
            print(
                f"  Google Books lookup "
                f"{idx}/{total}..."
            )

        if pd.isna(isbn) or not isbn:

            google_urls.append(None)
            google_large_urls.append(None)

            continue

        normal, large = fetch_google_cover(
            str(isbn),
            cache
        )

        google_urls.append(normal)
        google_large_urls.append(large)

        # Periodic cache save.
        if idx % 200 == 0:
            _save_cache(cache)

        time.sleep(0.05)

    # ----------------------------------------------------------
    # Save metadata
    # ----------------------------------------------------------

    item_meta["google_cover_url"] = (
        google_urls
    )

    item_meta["google_cover_url_large"] = (
        google_large_urls
    )

    _save_cache(cache)

    output_path = os.path.join(
        OUT_DIR,
        "item_meta.csv"
    )

    item_meta.to_csv(
        output_path,
        index=False
    )

    # ----------------------------------------------------------
    # Report
    # ----------------------------------------------------------

    n = len(item_meta)

    n_isbn = (
        item_meta["isbn13"]
        .notna()
        .sum()
    )

    n_img = (
        item_meta["image_url"]
        .notna()
        .sum()
    )

    n_google = (
        item_meta["google_cover_url"]
        .notna()
        .sum()
    )

    n_google_large = (
        item_meta["google_cover_url_large"]
        .notna()
        .sum()
    )

    print(
        f"Added isbn13 to "
        f"{n_isbn}/{n} books "
        f"({n_isbn / n:.1%})"
    )

    print(
        f"Added image_url to "
        f"{n_img}/{n} books "
        f"({n_img / n:.1%})"
    )

    print(
        f"Added google_cover_url to "
        f"{n_google}/{n} books "
        f"({n_google / n:.1%})"
    )

    print(
        f"Added google_cover_url_large to "
        f"{n_google_large}/{n} books "
        f"({n_google_large / n:.1%})"
    )

    print(
        "item_meta.csv columns now:",
        list(item_meta.columns)
    )


if __name__ == "__main__":
    main()